#!/bin/bash
#
# Run the test suite when the test file changes.

if ! command -v inotifywait >/dev/null 2>&1 ; then
  echo "inotifywait executable not found in path!"
  exit 1
fi

inotifywait -e close_write -m . |
while read -r directory events filename; do

  if [[ "$filename" == "test_all.sh" ]]; then
    clear
    echo "---"
    ../siif .
  fi
done
